[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "orbital_engine"
version = "1.3.0"
description = "A hierarchical N-body orbital mechanics engine"
authors = [
  { name="Anthony", email="antsstar@hotmail.com" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "sqlalchemy>=2.0.0"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",  # Helpful for seeing which lines of code aren't tested yet
    "mypy",
    "pandas-stubs"
]
dev = [
    "ipykernel",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]